import pandas as pd
import xgboost as xgb
import m2cgen as m2c
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

def main():
    print("1. Loading dataset...")
    try:
        df = pd.read_csv("real_training_data.csv")
    except FileNotFoundError:
        print("Error: real_training_data.csv not found.")
        return

    df["Label"] = df["Label"].astype(int)

    X = df[["NumPipes", "NumFlags", "IsSudo", "ObfuscationChars"]]
    y = df["Label"]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    print("\n2. Training XGBoost Model...")
    model = xgb.XGBClassifier(
        n_estimators=15,
        max_depth=4,
        learning_rate=0.2,
        objective="binary:logistic",
        base_score=0.5, 
        random_state=42
    )
    
    model.fit(X_train, y_train)

    print("\n3. Transpiling Model to Native Go...")
    raw_go_code = m2c.export_to_go(model)
    
    clean_lines = []
    for line in raw_go_code.split('\n'):
        if line.startswith('package ') or line.startswith('import '):
            continue
        clean_lines.append(line)
    
    clean_go_code = '\n'.join(clean_lines)
    
    final_go_file = f"""package tier1

import "math"

// Model represents our compiled XGBoost Gradient Boosted Tree.
// This file was AUTO-GENERATED by train_model.py via m2cgen.
type Model struct{{}}
{clean_go_code}

// Score takes the feature vector and returns a probability [0.0 - 1.0]
func (m *Model) Score(features []float32) float32 {{
	input := make([]float64, len(features))
	for i, v := range features {{
		input[i] = float64(v)
	}}

	rawScore := score(input)[0]
	probability := 1.0 / (1.0 + math.Exp(-rawScore))
	
	return float32(probability)
}}
"""

    print("4. Writing pkg/tier1/model.go...")
    with open("pkg/tier1/model.go", "w") as f:
        f.write(final_go_file)


if __name__ == "__main__":
    main()